### ISSUE TITLE
Initial database not loading

### ISSUE THREAD

**Issue by robbat2** [mlsecproject/gglsbl-rest#22]
Using Image ID 4564f0f5fc40 per mlsecproject/gglsbl-rest:latest

```
$ docker run -e GSB_API_KEY=$APIKEY -p 127.0.0.1:5000:5000 mlsecproject/gglsbl-rest 
2019-01-25T22:25:22+0000 pid=1 glogging INFO Starting gunicorn 19.9.0
2019-01-25T22:25:22+0000 pid=1 config INFO Initial database load...
2019-01-25T22:25:22+0000 pid=1 config INFO Update started as PID 7
2019-01-25T22:25:22+0000 pid=7 update INFO opening database at /home/gglsbl/db/sqlite.db
Traceback (most recent call last):
  File "update.py", line 32, in <module>
    update_hash_prefix_cache()
  File "/usr/lib/python3.6/site-packages/pid/decorator.py", line 14, in decorator
    return func(*func_args, **func_kwargs)
  File "update.py", line 17, in update_hash_prefix_cache
    sbl = SafeBrowsingList(gsb_api_key, dbfile, True)
  File "/usr/lib/python3.6/site-packages/gglsbl/client.py", line 34, in __init__
    self.api_client = SafeBrowsingApiClient(api_key, discard_fair_use_policy=discard_fair_use_policy)
  File "/usr/lib/python3.6/site-packages/gglsbl/protocol.py", line 81, in __init__
    self.service = build('safebrowsing', 'v4', developerKey=developer_key, cache_discovery=False)
  File "/usr/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/googleapiclient/discovery.py", line 222, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "/usr/lib/python3.6/site-packages/googleapiclient/discovery.py", line 272, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1924, in request
    cachekey,
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1501, in _conn_request
    conn.connect()
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1356, in connect
    raise socket_err
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1289, in connect
    sock.connect((self.host, self.port))
  File "/usr/lib/python3.6/site-packages/httplib2/socks.py", line 501, in connect
    _orgsocket.connect(self, (self.__proxy[1], portnum))
ConnectionRefusedError: [Errno 111] Connection refused
2019-01-25T22:25:22+0000 pid=1 config INFO Update process finished with status code 1
```

**Comment by asieira** [comment]
Hi, I think this line tells you it's likely a connectivity problem:
```
ConnectionRefusedError: [Errno 111] Connection refused
```

It seems like the [gglsbl](https://github.com/afilipovich/gglsbl) package is failing to connect to the Google Safe Browsing API endpoint. 

Do you need a proxy to reach out to the Internet? If that is the case, you'll need to set HTTP_PROXY and/or HTTPS_PROXY environment variables on the Docker container so it does too.

**Comment by robbat2** [comment]
No, no proxy required here. The plain sblookup/sbserver tooling from Google works fine as a comparision.

**Comment by asieira** [comment]
Interesting. I just ran the same test as you did with a valid Google Safe Browsing API key and everything worked as planned. 

First thing I'll ask is if using `-e 'GSB_API_KEY=$APIKEY'` with quotes makes any difference. Can you check that? 

Also, let's simplify the test and just use the gglsbl CLI client to see if we can further identity where the problem lies. Try this and let me know what result you get:
```
$ docker run -ti alpine:3.8
/ # apk update ; apk upgrade ; apk add -u python3 py3-pip
/ # pip3 install gglsbl
(...)
/ # gglsbl_client.py --db-path ./gglsbl.db --api-key '<YOUR API KEY HERE>' --onetime
2019-02-01 11:54:39,539 WARNING Circumventing request frequency throttling is against Safe Browsing API policy.
2019-02-01 11:54:40,179 INFO Opening SQLite DB ./gglsbl.db
2019-02-01 11:54:40,179 INFO SQLite DB does not exist, initializing
2019-02-01 11:54:40,181 INFO Cleaning up full_hash entries expired more than 43200 seconds ago.
(...)
```

This forces a database download to the file specified. Let me know if this works for you or what errors you get otherwise.

**Comment by asieira** [comment]
It would be interesting to try that outside of Docker as well, by the way.

**Comment by asieira** [comment]
Hi @robbat2, have you had the opportunity to test this?

**Comment by robbat2** [comment]
My host box crashed due to an unrelated kernel issue, and now I can't reproduce the problem anymore. I'm wondering if Docker had something funked up; it wouldn't be the first time.

**Comment by asieira** [comment]
Glad to hear the problem was fixed! Hope you enjoy using gglsbl-rest.
